services:
  web:
    build: .
    environment:
      - OPENAI_API_KEY=
      - SUPABASE_URL=
      - SUPABASE_ANON_KEY=
      - GROQ_API_KEY=
      - TOKENIZERS_PARALLELISM=
      - REDIS_URL=
      - REDIS_PASSWORD=
      - REDIS_PORT=
      - REDIS_USERNAME=
      - MXBAI_API_KEY=
      - RESEND_API_KEY=
      - RESEND_NOREPLY=

    ports:
      - "8080:8080"
